global:
  message: Welcome to the microservice project

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    health:
      show-details: always
