server:
  port: 8762

spring:
  application:
    name: eureka-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    
management:
    endpoints:
        web:
            exposure:
                include: "*" 
    endpoint:
        health:
            access: unrestricted
        info:
            access: unrestricted
        metrics:
            access: unrestricted
        prometheus:
            access: unrestricted

    metrics:
        tags:
            application: ${spring.application.name}
        
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
