server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:${HOSTNAME:localhost}}
    prefer-ip-address: ${EUREKA_PREFER_IP:false}
    instance-id: ${spring.application.name}:${server.port}
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

info:
  app:
    name: gateway-server
    description: API Gateway for microservices (Java Config)
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, refresh, circuitbreakerevents, prometheus
        
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
