server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          
eureka:
  instance:
    prefer-ip-address: true     # always register using IP instead of hostname
    hostname: ${HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

info:
  app:
    name: gateway-server
    description: API Gateway for microservices (Java Config)
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, metrics
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
