server:
  port: 8072

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

info:
  app:
    name: gateway-server
    description: API Gateway for microservices (Java Config)
    version: 1.0.0
