spring:
  application:
    name: gateway-server
    
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

eureka:
  instance:
    prefer-ip-address: true     # always register using IP instead of hostname
    hostname: ${HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, metrics
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
