spring:
  application:
    name: order-service

eureka:
  instance:
    prefer-ip-address: true     # always register using IP instead of hostname
    hostname: ${HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

info:
  app:
    name: order-service
    description: order Management Microservice
    version: 1.0.0
  company:
    name: MyCompany
    website: https://mycompany.com

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, metrics
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
